name: ose-code-templates

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
  - python=3.7
  - sphinx>=1.4
  - pip
  - numpy
  - numba
  - jupyterlab
  - jupyter_contrib_nbextensions
  - mpi4py
  - black
  - pytest
  - pytest-cov
  - pytest-repeat
  - pytest-mpi
  - pandas
  - fastparquet
  - python-snappy
  - cloudpickle
  - chaospy
  - estimagic
  - pytest-flake8
  - pip:
    - git+https://github.com/OpenSourceEconomics/respy.git
    - sphinx_rtd_theme
    - nbsphinx
    - pytest-black
    - sphinxcontrib-bibtex
    - black-nb
    - flake8-nb


