name: ose-code-templates

channels:
  - defaults
  - opensourceeconomics
  - conda-forge

dependencies:
  - python=3.7
  - sphinx>=1.4
  - pip
  - numpy
  - numba
  - jupyterlab
  - jupyter_contrib_nbextensions
  - mpi4py
  - black
  - pytest
  - pytest-cov
  - pytest-black
  - pytest-repeat
  - pytest-mpi
  - pip:
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-bibtex


