name: CI

on: [push]

jobs:
  run-tests:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - used: codecov/codecov-action@v1
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        acitvate-environment: ose-code-templates
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - name: install mpich dependency
      run: |
        sudo apt-get update
        sudo apt-get install mpich
    - name: scalar testing with coverage report
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: parallel testing
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        cd templates/01_embarssingly_parallel_loop
        mpiexec -n 1 -usize 3 python run.py
        mpiexec -n 1 -usize 3 pytest
